#ifndef CONFIG_HPP
#define CONFIG_HPP

const int DEFAULT_STATION_COUNT = 6;
const int DEFAULT_ROUTE_COUNT = 5;
const int DEFAULT_TRAIN_COUNT = 5;
const float DEFAULT_TRAIN_SPEED = 70.0f;
const int STATION_DWELL_TIME_MIN = 2;
const int STATION_DWELL_TIME_MAX = 5;
const int SIMULATION_START_HOUR = 6;
const int SIMULATION_START_MINUTE = 0;
const int SIMULATION_STEP = 15;
const float STATION_DISTANCE_STEP = 50.0f;
const int ACCIDENT_INTERVAL_MIN = 2;
const int ACCIDENT_INTERVAL_MAX = 15;
const int ACCIDENT_DURATION_MIN = 30;
const int ACCIDENT_DURATION_MAX = 120;
const int DELAY_MIN = 1;
const int DELAY_MAX = 5;
const float DELAY_PROBABILITY = 0.30f;
const int WINDOW_WIDTH = 1400;
const int WINDOW_HEIGHT = 800;
const int FPS = 30;
const int PANEL_WIDTH = 250;
const int RAILWAY_LEFT_MARGIN = 280;
const int RAILWAY_TOP_MARGIN = 100;
const int RAILWAY_TRACK_HEIGHT = 400;
const int STATION_RADIUS = 15;
const int TRAIN_WIDTH = 25;
const int TRAIN_HEIGHT = 15;
const int SCHEDULE_WINDOW_WIDTH = 600;
const int SCHEDULE_WINDOW_HEIGHT = 500;
const int STATS_WINDOW_WIDTH = 600;
const int STATS_WINDOW_HEIGHT = 500;

#endif
